---
apm_server_config_template_path: "{{ playbook_dir }}/templates/config"

#install_mode: deb

elasticsearch_api_host: elasticsearch
elasticsearch_api_port: 9200

kibana_elasticsearch_hosts: ['http://{{ elasticsearch_api_host }}:{{ elasticsearch_api_port }}']

## Elastic
#elasticsearch_version: "{{ apm_server_version }}"
#elasticsearch_config: "{{ elasticsearch_default_config | combine(vars['elasticsearch_' ~ apm_server_version.split('.')[0] ~ '_extra_config'])}}"
#
#elasticsearch_default_config:
#  node.name: "{{ elasticsearch_api_host }}"
#  cluster.name: idealista-cluster
#  network.host: _site_
#  discovery.type: single-node
#  http.port: "{{ elasticsearch_api_port }}"
#  bootstrap.memory_lock: true
#  xpack:
#    security:
#      enabled: false
#
#elasticsearch_7_extra_config:
#
#elasticsearch_8_extra_config:
#  xpack:
#    security:
#      enabled: false
#      autoconfiguration:
#        enabled: false
#      http:
#        ssl:
#          enabled: false
#      transport:
#        ssl:
#          enabled: false
#
#elasticsearch_heap_size: "256m"
#elasticsearch_os_tuning: false